RESTWS-813: Compared strings using .equals instead of == and !=
openmrs/openmrs-module-webservices.rest pull request #448
Opened 2020-09-22 06:57 UTC by insookwa

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-813

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2020-09-22 10:48 UTC, sacull commented
It seemed to me that such tickets would be too easy for you. ;)

However, you forgot to add the "RESTWS-813:" tag to the commit description:
![image](https://user-images.githubusercontent.com/9057882/93873392-ee06aa00-fcd1-11ea-82ac-6284680c5631.png)

Additionally, I am curious what tests have you added? : P
From the description of PR:
![image](https://user-images.githubusercontent.com/9057882/93873183-8ea89a00-fcd1-11ea-8672-2a4639170cc7.png)

2020-09-23 05:32 UTC, HerbertYiga commented
@insookwa  Add a ticket Id to your commit,https://wiki.openmrs.org/display/docs/Pull+Request+Tips

2020-11-20 10:43 UTC, sacull commented
@insookwa Are you still working on it?

2020-11-21 18:49 UTC, insookwa commented
oh, can I make another commit including the ticket ID to have this closed  ? about the tests i added none @sacull

2020-11-21 19:19 UTC, insookwa commented
> @insookwa Are you still working on it?

I need to close this  by adding the ticket ID on the commit . do you know how i can do that @sacull  @HerbertYiga

2020-11-21 20:04 UTC, insookwa commented
> It seemed to me that such tickets would be too easy for you. ;)
> 
> However, you forgot to add the "RESTWS-813:" tag to the commit description:
> ![image](https://user-images.githubusercontent.com/9057882/93873392-ee06aa00-fcd1-11ea-82ac-6284680c5631.png)
> 
> Additionally, I am curious what tests have you added? : P
> From the description of PR:
> ![image](https://user-images.githubusercontent.com/9057882/93873183-8ea89a00-fcd1-11ea-8672-2a4639170cc7.png)

Thanks @sacull  i have  made a rebase and edited the commit message . please review and revert

2020-11-21 20:16 UTC, dkayiwa commented
> review and revert

revert or merge 😊

2020-11-21 20:22 UTC, sacull commented
> i have made a rebase and edited the commit message

If so, only locally, because PR still contains commit from September. Additionally, there is some conflict, so you will have to resolve it.

2020-11-23 14:22 UTC, insookwa commented
> > review and revert
> 
> revert or merge

work in progress

2020-11-23 14:24 UTC, insookwa commented
> > i have made a rebase and edited the commit message
> 
> If so, only locally, because PR still contains commit from September. Additionally, there is some conflict, so you will have to resolve it.

@sacull please en light me about the conflict . how can i solve it

2020-11-23 15:15 UTC, sacull commented
The easiest way to use Github.

![image](https://user-images.githubusercontent.com/9057882/99978633-7a9f1880-2da6-11eb-9c7b-0e7356e75bf9.png)

Delete lines 1040, 1043-1045:
![image](https://user-images.githubusercontent.com/9057882/99978869-c225a480-2da6-11eb-8823-68ae2120ab20.png)

![image](https://user-images.githubusercontent.com/9057882/99979075-06b14000-2da7-11eb-89fe-2a6393ad5d18.png)
You'll probably get on with it. This is the easiest method, but not necessarily the best. ;)

2020-11-24 18:24 UTC, sacull commented on omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
> +
```suggestion
		if (operationName.equals("post") || operationName.equals("get")) {
			//			createDefinition(operationEnum, resourceName, resourceParentName, representation);
```
Don't you think these blank lines are unnecessary?

2020-11-24 18:25 UTC, sacull commented on omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
>  			createDefinition(operationEnum, resourceName, resourceParentName, resourceHandler);
```suggestion
		if (operationName.equals("post") || operationName.equals("get")) {
			//			createDefinition(operationEnum, resourceName, resourceParentName, representation);
			createDefinition(operationEnum, resourceName, resourceParentName, resourceHandler);
```
Don't you think these blank lines are unnecessary?

2020-11-24 18:27 UTC, sacull commented on omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
>  			createDefinition(operationEnum, resourceName, resourceParentName, resourceHandler);
And is this code in the comment needed?

2020-12-30 14:52 UTC, sacull requested changes

2020-12-30 14:52 UTC, sacull commented on omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
> +
```suggestion
```
This fragment should be removed, otherwise, the code will not compile.

2023-03-21 21:37 UTC, closed without merging

2023-03-27 04:13 UTC, njiddasalifu commented
Hi @dkayiwa can I continue work on this issue. I see it cosed