RESTWS-885: Reset password REST endpoint requires privileges
openmrs/openmrs-module-webservices.rest pull request #590
Opened 2023-09-18 16:22 UTC by IamMujuziMoses

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-885

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2023-09-18 16:26 UTC, IamMujuziMoses commented
@mseaton @dkayiwa please review

2023-09-18 17:00 UTC, mseaton requested changes

2023-09-18 17:00 UTC, mseaton commented on omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/PasswordResetController2_2.java
> +		if (user == null || user.getUserId() == null ) {
If the previous implementation did not throw an exception if user is null, we shouldn't do so here either.  For example, if you try to hit this, and get an exception, you know that username / email doesn't exist.  That may not be information we want to expose.

Just simplify this method and do everything inside of the try/finally block.  No need to declare the user outside of this block, and then use this user outside of this block.  Something like:

```
try {
  Context.addProxyPrivilege(PrivilegeConstants.GET_USERS);
  User user = userService.getUserByUsernameOrEmail(usernameOrEmail);
  if (user != null {
    userService.setUserActivationKey(user);
  }
}
finally {
  Context.removeProxyPrivilege(PrivilegeConstants.GET_USERS);
}
```

2023-09-18 18:48 UTC, mseaton approved these changes
LGTM, thanks!

2023-09-19 13:15 UTC, dkayiwa commented on omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/PasswordResetController2_2Test.java
> +		assertNotNull(dao.getLoginCredential(user).getActivationKey());
Can you assert that this was null before the REST call?

2023-09-23 19:29 UTC, dkayiwa commented
@IamMujuziMoses your test is not testing the changes in `PasswordResetController2_2` because it passes without those changes.

2024-11-12 16:11 UTC, mherman22 commented
@IamMujuziMoses is this still on your radar?

2024-11-13 09:49 UTC, IamMujuziMoses commented
@mherman22, you can pick it up and work on it

2024-11-15 05:51 UTC, mherman22 commented
> @IamMujuziMoses your test is not testing the changes in `PasswordResetController2_2` because it passes without those changes.

@dkayiwa I have reverted the `PasswordResetController2_2` to its originality and ran the tests and the two tests that were added are failing with somewhere along the lines of **`org.openmrs.api.APIAuthenticationException: error.privilegesRequired`** 

And when i add the changes in that class, the tests pass.

2025-06-16 18:13 UTC, IamMujuziMoses commented
> @IamMujuziMoses your test is not testing the changes in `PasswordResetController2_2` because it passes without those changes.

@dkayiwa they are actually testing the changes in `PasswordResetController2_2`, the previous tests before the change are passing because their REST call is called with an `Admin` user since they don't log out prior to the call, but the changes help: 
- The logged-in `Authenticated` user, even without privileges, to make the REST call.
- The `UnAuthenticated` user, also can make the REST calll.

2025-06-18 14:17 UTC, dkayiwa commented
So, of what value is the test, if it still passes even without these changes? I thought that the test would be written in such a way that if anyone tried to remove your fix, the test would immediately fail.

2025-06-18 19:02 UTC, IamMujuziMoses commented
@dkayiwa perhaps this video might help illustrate what happened.

https://github.com/user-attachments/assets/8a5aa32f-0ad1-4638-8a53-83db6ee7b502

2025-06-26 11:18 UTC, dkayiwa commented
Can you look into these merge conflicts?

2025-06-26 22:10 UTC, merged