(O3-3551): Improvement GitHub Actions - Use Latest versions of actions
openmrs/openmrs-module-webservices.rest pull request #614
Opened 2024-07-04 19:47 UTC by Bcoderx6

This pull request updates the GitHub Actions workflow to utilize the latest versions of several key actions, improving performance, security, and feature set. The specific updates include:

1.actions/checkout: Updated from `v2` to `v4`.
2. actions/cache: Updated from `v2` to `v3`.
3.actions/setup-java: Updated from `v1` to `v3`.

Benefits:
- Enhanced Performance: The latest versions come with performance improvements, which can speed up the workflow execution.
- Improved Security: Newer versions include the latest security patches, reducing the risk of vulnerabilities.
- Advanced Features: The updated actions provide additional features and improvements, such as better caching mechanisms and more robust setup options for Java.

Detailed Changes:
1. actions/checkout@v4
   - Improved performance and reliability in fetching the repository.
   - Enhanced support for submodules and large repositories.

2. actions/cache@v3
   - Optimized caching strategies to reduce build times.
   - Better handling of cache keys and restore-keys, ensuring more efficient cache usage.

3. actions/setup-java@v3
   - Better support for multiple Java versions and configurations.
   - Improved caching of Java dependencies, reducing setup times.

2024-07-04 19:51 UTC, Bcoderx6 commented
@jayasanka-sack! , Kindly review the updates made to the GitHub Actions workflow.

2024-07-08 11:18 UTC, jayasanka-sack requested changes
Thanks for the PR, @Bcoderx6 ! Could you please address the requested changes?

2024-07-08 11:18 UTC, jayasanka-sack commented on .github/workflows/maven.yml
> +        uses: actions/setup-java@v3
```suggestion
        uses: actions/setup-java@v4
```

2024-07-08 11:18 UTC, jayasanka-sack commented on .github/workflows/maven.yml
> +        uses: actions/cache@v3
```suggestion
        uses: actions/cache@v4
```

2024-07-08 17:32 UTC, Bcoderx6 commented
@jayasanka-sack ! Fine, I've done those changes.

2024-07-09 11:15 UTC, jayasanka-sack commented on .github/workflows/maven.yml
> +        uses: actions/setup-java@v4
```suggestion
        uses: actions/setup-java@v4
        distribution: 'zulu'
```

2024-07-09 11:16 UTC, jayasanka-sack commented on .github/workflows/maven.yml
>            java-version: ${{ matrix.java-version }}
```suggestion
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'
```

2024-07-09 11:18 UTC, jayasanka-sack commented on .github/workflows/maven.yml
> +          distribution: 'zulu'
```suggestion
          distribution: 'temurin'
```

2024-07-09 11:30 UTC, merged